### ISSUE TITLE
Week of 10/9/2023

### ISSUE THREAD

**Issue by glenncampagna** [HARPgroup/HARParchive#1114]
**Water Availability**
- **Goal**: "What impact does model vs. gage calibration error have on our assessment of water availability, and/or flow alteration?"
- [ ] Water availability article: [Estimating 7Q10 confidence limits from data: a bootstrap approach DP Ames - Journal of water resources planning and management, 2006 - ascelibrary.org](https://ascelibrary.org/doi/10.1061/%28ASCE%290733-9496%282006%29132%3A3%28204%29) --> see who’s cited it, and summarize how folks are calculating uncertainty for streamflow records
- [ ] Test om pull request  https://github.com/HARPgroup/om/pull/501 once R script sudo command is obtained #1108 
  - [ ] If successful, merge
- [ ] After above: tasks for another om pull request laid out in https://github.com/HARPgroup/HARParchive/issues/818#issuecomment-1725373771
- [ ] USGS model metrics tasks for gage vs model rmd laid out in https://github.com/HARPgroup/HARParchive/issues/1101#issue-1902866421

**Regional Summary Rmd**
- Crs error from last week seems to have been resolved, make sure all analysts get same result #1106 
- New ggmap bug required a work-around for the basemap that is not robust #1113 
- [ ] Continue working to turn what we have into a full document
- [ ] Ensure use of new foundation file is as efficient as possible
- [ ] Update the detailed work plan to show more of what we have, get questions that we can ask soon before new generation
