### ISSUE TITLE
Week of 10/23/2023

### ISSUE THREAD

**Issue by glenncampagna** [HARPgroup/HARParchive#1121]
**Water Availability**
- [ ] Tasks for another om pull request laid out in https://github.com/HARPgroup/HARParchive/issues/818#issuecomment-1725373771
- [ ] USGS model metrics tasks for gage vs model rmd laid out in https://github.com/HARPgroup/HARParchive/issues/1101#issue-1902866421

**Regional Summary Rmd**
- [ ] Base map alternative: may be primitive (no topo, land cover?)  but VGIN https://vgin.vdem.virginia.gov/pages/base-mapping
- [ ] Explore modularizing mapping function https://github.com/HARPgroup/HARParchive/issues/1106#issuecomment-1749533265
- [ ] Continue working to turn what we have into a full document
- [ ] Ensure use of new foundation file is as efficient as possible
- [ ] Update the detailed work plan to show more of what we have, get questions that we can ask soon before new generation

**Comment by glenncampagna** [comment]
### 10/20 meeting notes 
- The current method of getting a basemap is not robust and requires an API key saved to the environment 
- [ ] We don't want our map to depend on the basemap, meaning we want to be able to have a 'blank' map generated without a basemap

**Comment by glenncampagna** [comment]
### Map using VGIN basemap and cropping layers to spatial extent
<img width="1009" alt="image" src="https://github.com/HARPgroup/HARParchive/assets/104520197/6fd219f9-c07d-48b2-b457-ff1f4c5d4dbf">



- Cropping by our bbox extent works for borders and road lines, ex `borders <- st_crop(borders, bbox_sf)`
- The same process doesn't work as intended for our text labels, so a scale is applied to the label layer:
```
geom_text_repel(data = labelsP ...) +
    scale_x_continuous(limits = bbox_points$x, expand = c(0, 0)) +
    scale_y_continuous(limits = bbox_points$y, expand = c(0, 0))   
```

**Comment by rburghol** [comment]
memoise implementation for caching

#### Add to `config.local.private`
```
# set up a caching function for NWIS
Sys.setenv(USGS_cache_dir = "/media/model/usgs")

```

#### Add to `config.R`
```
# set up a caching function for NWIS
library("memoise")
dir <- Sys.getenv("USGS_cache_dir")
if (dir == "") {
  dir <- tools::R_user_dir(package="dataRetrieval", which="cache")
}
if (!dir.exists(dir)) {
  dir.create(dir, recursive=TRUE)
}
# maybe don't use this just yet.
#unlink(dir, recursive = TRUE, force = TRUE)
db <- memoise::cache_filesystem(dir)
one_day <- 24*60^2
# create caching function wrappers for readNWISdv and readNWISsite
memo_readNWISdv <- memoise::memoise(dataRetrieval::readNWISdv, ~memoise::timeout(one_day), cache = db)
memo_readNWISsite <- memoise::memoise(dataRetrieval::readNWISsite, ~memoise::timeout(one_day), cache = db)

```
