### ISSUE TITLE
Week of 11/14/2023 & Thanksgiving Break

### ISSUE THREAD

**Issue by glenncampagna** [HARPgroup/HARParchive#1129]
**Regional Summary Rmd**
- [ ] Explore modularizing mapping function https://github.com/HARPgroup/HARParchive/issues/1106#issuecomment-1749533265
  - We can define multiple functions within the same file for tidiness 
- [ ] Make appropriate changes once permit status has been added to our foundational data 
- [ ] add ability to run Rmd without showing maps, ex. by adding a show_map param
- [ ] Functionalize % diff calculation in Dataframe_Generator: `pct_diff(data, column1, column2, new_col)`
- [ ] Explore memoise package for cahcing data, for example nhd data https://github.com/HARPgroup/HARParchive/issues/1121#issuecomment-1810623966
- [ ] Create new issue for summary RMD examples
  - [ ] Add several examples with different origin types and featr types, including DF generator and RMD render commands used 

**Water Availability**
- [ ] Tasks for another om pull request laid out in https://github.com/HARPgroup/HARParchive/issues/818#issuecomment-1725373771
  - Remember to do a fresh pull of om

**Comment by gmahadwar** [comment]
Foundation data with column of permit limit in mgy, or status of exempt/non-permitted has been added to repo, and is ready to incorporate.
@EllaF21 @megpritch @glenncampagna
