### ISSUE TITLE
Week of 12/18/2023

### ISSUE THREAD

**Issue by glenncampagna** [HARPgroup/HARParchive#1136]
- **Meeting Tues 12/19 @ 11:00 am**

### Regional Summary RMD & DF Generator 
- [ ] Debug basemap function within mapgen, make bbox_points an arg for the function 
  - [ ] Test w/ previously non-working origins and update #1130 
- [ ] Modularize mapping function https://github.com/HARPgroup/HARParchive/issues/1106#issuecomment-1749533265
  - We can define multiple functions within the same file for tidiness 
- [ ] Make changes to incorporate new permit status in foundational data (DF gen)
- [ ] Implement % difference function in DataframeGenerator 
- [ ] Explore memoise package for caching data, for example nhd data https://github.com/HARPgroup/HARParchive/issues/1121#issuecomment-1810623966
- [ ] Review and merge Rob's PR for the DF generator https://github.com/HARPgroup/HARParchive/pull/1135/files
  - [ ] Replace RomFeature + RomProperty retrieval for riverseg model data with `om_vahydro_metric_grid()`
- [ ] Begin CU analysis -- read in `consumptive_use_frac` with `om_vahydro_metric_grid`
  - Example of where these vars are stored, within rivseg model scenarios http://deq1.bse.vt.edu/d.dh/om-model-info/5328150

### Water Availability
- [ ] Tasks for another om pull request laid out in https://github.com/HARPgroup/HARParchive/issues/818#issuecomment-1725373771
  - Remember to do a fresh pull of om 

### Organization
- [ ] Update the ReadMe for the regional summary rmd including: workflow w/ df generator, params, localities available, regions available, example basins for major rivers 
- [ ] Review weekly issues from the summer and make sure no tasks got left behind

**Comment by glenncampagna** [comment]
### Changes to rsegs df resulting from now using metric grid to get modeled metrics https://github.com/HARPgroup/HARParchive/pull/1135
- Geometry was originally stored in a `WKT` column, now the column is `geom`
- New `pid` column 
- `featureid` column added, which matches `hydroid` column
- `name` and `propname` columns (same)

**Comment by glenncampagna** [comment]
### R syntax question in `waterSupplyElement.R`
I'm in the process of moving the Smin calculations to the already existing imp_off or imp_enabled blocks and I'm unsure of the meaning of the syntax used here:

```
if (pump_store || !imp_enabled) {
  flow_ts <- ddat2$Qintake
  flow_ts_name = "Source Stream"
} else {
  flow_ts <- ddat2$impoundment_Qin
  flow_ts_name = "Inflow"
}
```
Specifically the `|| !`

It seems like Smin lines should go within the else part

**Comment by glenncampagna** [comment]
### Dataframe Generator RMD and render 
To make the workflow with our dataframe generator and WSP regional summary maker easiest I made the DF generator into a RMD also so it's renderable:
https://github.com/HARPgroup/HARParchive/blob/master/HARP-2023-Summer/Dataframe_Generator.Rmd
```
rmarkdown::render("~/Desktop/GitHub/HARParchive/HARP-2023-Summer/Dataframe_Generator.Rmd", 
                  params = list(
                      origin = "Roanoke_1", 
                      origin_type = "region", 
                      featr_type = "facility", 
                      metric_mod = "wd_mgd", 
                      model_version = "vahydro-1.0",
                      metric_feat = "wsp2020_2040_mgy", 
                      rivseg_metric = c("l30_Qout", "l90_Qout"), 
                      runid_list = c("runid_11", "runid_13"), 
                      crs_default = 4326, 
                      limit_featrs_to_origin = FALSE,
                      overwrite_files = TRUE, 
                      base_layer_data = FALSE))
```

- [ ] Update #1130

**Comment by glenncampagna** [comment]
### 12/29 Meeting Updates 
- Significant differences can be seen between the actual baseline scenario (runid_0) L30/90s and those back-calculated from a demand scenario (ex. runid_11) w/ the formula `Qout_base = Qout_demand + wd_cumulative_mgd - ps_cumulative_mgd`
  - This is because the back-calculation method is flawed due to reservoir operations and pump-store, which is why we will always use the baseline scenario metrics if they exist in our WA equation
  - In headwaters and basins without upstream impediments, meaning structures like dams aren't impeding the flow, the baseline scenario and approximation should be nearly the same 
- Analysts will be creating a 'White-Paper' document on Water Availability where we explain the choices we've made,  methods we have in place, and more

**Comment by glenncampagna** [comment]
### New REST password @megpritch @EllaF21 
When you're back online, the REST password in your `/var/www/R/auth.private` should be updated:
`rest_pw <- 'H@RPd@t@2024'`
