### ISSUE TITLE
Water Availability White Paper

### ISSUE THREAD

**Issue by glenncampagna** [HARPgroup/HARParchive#1149]
Document: https://github.com/HARPgroup/HARParchive/blob/master/HARP-2023-Summer/WaterAvailability_Documentation.docx

**To-do:**
- [ ] Background/Introduction: why is this important, why did we create this method?
- [ ] Equation and variables with reasoning for decisions 
- [ ] Specific examples: plugging in values to the equation (one positive, one neg.)
- [ ] Storage and Smin
- [ ] Baseline model scenario
- [ ] Error
