### ISSUE TITLE
Water Availability Case Studies 

### ISSUE THREAD

**Issue by glenncampagna** [HARPgroup/HARParchive#1156]
**Description:**

A case study is a descriptive example of a particular area (ex. a watershed/region) where water availability is calculated. For that example watershed, we can take a detailed look at the individual calculations and resulting values generated.
- You would generate a table of the different values of Smin for the reservoirs in that watershed, using the approximate and near-exact methods. We would look at how much those values differ.
  - 4 cases chosen to represent times when the Approximate method is and is not​ the lowest Smin value, as those are the approximate method is that which is assumed to give us the lowest possible values, and if it does not we want to know why (previously this only​ happened when we were using water year instead of calendar year). These 4 cases can be from different watersheds, as usually a few case studies are completed.
- Compile a table of overall values in all reservoirs with summary stats by method.
- You would generate a table (or in some way show) the available water calculated for each river segment in the watershed. If you take the table approach, the values of each variable in the equation would be the contents of the table, where rows would be each river segment and columns would be each variable.  We would use this to check whether the equation inputs and outputs generally make sense. 
- You would generate a graph of water available compared to demand and flow.  It could be a bar plot where the x-axis would be each river segment, the y-axis would be the WA calculated, and a second y-axis would show Qnsf or Qbaseline. We would use this to consider whether our calculations make physical sense for the watershed.
- Any particular notes about running this watershed calculation, any discussion about the results as noted above, would then get written down to accompany the tables/graphs and become the case study.

You've started to do some of these things already, it's just a matter of putting it all together for a collective look.
Focusing on doing case studies will be needed before the other documentation can actually be written, because results like the various Smin values will numerically justify our reason for choosing the approximate method, instead of just stating that we went with the approximate method based on assumptions.

from @gmahadwar 2/1/2024

**Tasks:**
- [ ] Decide on watersheds/riversegs to use for case studies, document the impoundments within 
- [ ] Create rmd for this process and lay out different sections 

**Related Scripts and Issues:**
https://github.com/HARPgroup/HARParchive/blob/master/HARP-2023-Summer/Smin_methods.R
https://github.com/HARPgroup/HARParchive/blob/master/HARP-2023-Summer/WA_methods.R
Smin #1140 
Water Availability #818

**Comment by glenncampagna** [comment]
### Initial 3 Table Previews 
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/b9e08fb5-03ba-477c-88b8-51c324beed73)
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/8a112579-bfed-4b97-a7eb-c194207edcef)
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/b3166356-e926-4894-8ec0-d68a55b47849)

**Comment by glenncampagna** [comment]
### Additional Table/Map/Graph Ideas 
- Table with the riversegs with the lowest WA values in the state 
  - This would support the map I have planned showing WA by riverseg using fill colors

**Comment by rburghol** [comment]
Hey @glenncampagna these are really shaping up. In terms of showing the lowest WA in the state, I think that the overall map of WA should do that implicitly. Moreover, we would expect small streams to have low W.A., and large streams to have higher WA, so that comparison may not really be relevant.

Looking at table 3, etc., I think an important piece of context should be wd_cumulative_mgd. Including that will allow us to draw connections.
Question: are you using 90% BASELINE as the  target MIF for calculating the portion of WA that comes from flow? I suppose you should indicate the target MIF as well.

**Comment by glenncampagna** [comment]
@rburghol Ok sounds good, I'll retrieve and include the wd_cumulative_mgd values in tables. I understand what you're saying about the table being somewhat redundant to the map in terms of WA values; I guess my thinking of the table was that it could be useful to see other metrics for the segments with the lowest WA (baseflow, demand, withdrawal which we'll be adding) and if those make sense.

The in stream flow coefficient is being multiplied by the base flow metric in the Water Availability equation, yes. I currently have the coefficient as an input to the script which I forgot to include (set to 0.9 for now). Are you saying that it'd be helpful to include in table titles? I'd agree with this since the other 2 important inputs (demand and baseline scenarios) are included in the titles/headers

**Comment by rburghol** [comment]
Hey @glenncampagna thanks for your thoughts. I think a separate table of lowest avail would be redundant, though if we had large negative values that could be og high interest.  

Thanks for confirming the 90% mif, and I was thinking add it as a column, i.e. L90 MIF, which would allow us to later reflect cases where we use ELFs to customize them by basin.  This will make the table fairly busy so we may regret this :)

**Comment by glenncampagna** [comment]
@rburghol Gotcha. Are you wanting the column to contain the actual minimum in stream flow values (MIF coefficient * Baseflow metric) or just the coefficient we're using?

**Comment by rburghol** [comment]
Actual would be my first guess - what do you think pros/cons @gmahadwar @glenncampagna

**Comment by gmahadwar** [comment]
MIF: Would decide based on how often is there a MIF that's separate
 - Pro is that we see the actual number being multiplied in the case where the MIF is NOT a PoF.  I'm referring to :
   -  $(PoF * Q_{LCPLbase})$ could be rewritten as $Q_{mif}$, where $Q_{mif}$ = minimum instream flow (if mif is NOT a PoF, and is knowable in a single period mean numeric form)
 - Con is that for the main cases where there is a PoF, we aren't showing the input variables of PoF and Q_{LCPLbase}
   - In these cases it is helpful to see the PoF and Q_{LCPLbase}

Third table: Also agree on the wd_cumulative_mgd in the third table, I'm thinking about if there are other helpful columns like cumulative point source (I assume that's ps_cumulative_mgd) or the L30/L90 value itself for the rseg, and the rseg flow out

**Comment by glenncampagna** [comment]
### Carvins question 
- When I use `OR3_7740_8271_carvins` to identify Carvins Cove as one of our case studies, `fn_extract_basin` fails to pull any upstream segments
- Is this because this rseg ID is unique to the reservoir? We talked about wanting to see Spring Hollow upstream of Carvins @rburghol , but I do not with the methods used so far

**Comment by rburghol** [comment]
@glenncampagna - this is because there are no upstream segments from Carvins, it is a headwater, so where you want to do it is with the outlet being Roanoke River in Roanoke, which will then have Carvin's, Tinker Creek and all the Roanoke segments upstream of Carvins.  Thus:
```
roaroa_data <- fn_extract_basin(wshed_data,'OR3_7740_8271')
```

**Comment by glenncampagna** [comment]
### Carvins update, similar Lake Anna question 
- Thanks @rburghol , that worked well:
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/fb2fc3cb-55ed-4c05-ad10-ba6fffd348c9)
- Ordering has been done so far by cumulative wd which doesn't give exactly the correct upstream -> downstream order we want. Next step will be ordering by rseg naming convention: `[prefix]_[this_seg]_[downstream_seg]`
- It looks like a similar thing to Carvins happens for Lake Anna where no upstream segs are found: 
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/3a8e5358-576a-4468-a735-661726f71c8e)
- Should I treat Lake Anna as a headwater also and use its downstream segment to pull upstream segments?

**Comment by glenncampagna** [comment]
### Graph preview for Carvins Cove watershed (upstream & downstream) @gmahadwar 
<img width="841" alt="image" src="https://github.com/HARPgroup/HARParchive/assets/104520197/2c69a5e5-d074-41f7-8068-e1de16164203">

**Comment by gmahadwar** [comment]
Thanks, @glenncampagna, can you write out the elements that go into Qavailable? Just adding to this comment is fine right now. I know you said it verbally but would be helpful for reference to explain this graph.

**Comment by rburghol** [comment]
Error `! object 'table_imp' not found` testing with the following:
```
rmarkdown::render(paste0(github_location,"/HARP-2023-Summer/WaterAvailability/WaterAvailability_CaseStudies.Rmd"), 
                  output_file = paste0(export_path,"/WAcasestudies_knit_runid11_runid0_0.9.docx"),
                  output_format = "word_document",
                  params = list(
                      demand_scenario = 'runid_11', 
                      baseline_scenario = 'runid_0', 
                      mif_coef = 0.9))
```

**Comment by glenncampagna** [comment]
### No baseline for Lake Anna watershed 
The only case study we've chosen where it appears the baseline scenario has not been run yet is Lake Anna:
<img width="1134" alt="image" src="https://github.com/HARPgroup/HARParchive/assets/104520197/65ea5605-7b76-49db-a722-0e8a51816736">
<img width="819" alt="image" src="https://github.com/HARPgroup/HARParchive/assets/104520197/7ab1bccc-f2c9-4056-aa44-3281a34fe118">
- Should I check `runid_100` also for baseline data? @rburghol I currently only check `runid_0`

**Comment by glenncampagna** [comment]
### Lake Chesdin case study mystery basins 
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/13e5a0d9-390d-4380-8cce-0a12b6dbd604)

**Comment by glenncampagna** [comment]
Where is the function `vahydro_post_metric_to_scenprop()` created? I don't believe we have ever loaded it in R before and only used it in R via the command line

**Comment by glenncampagna** [comment]
### Map/Table Preview
**Lake Manassas:**
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/06d90fb9-7fa8-4d43-b185-ef19cd5b03bd)
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/999754b5-53ca-4542-9ad1-af7c9976444a)
- [ ] Table would be better if it was L30-specific for this map
- [ ] Indicate the column napped in the flextable?

**Comment by glenncampagna** [comment]
### Lake Chesdin WA L90 Map & Table + Questions 
<img width="946" alt="image" src="https://github.com/HARPgroup/HARParchive/assets/104520197/4845f289-dc06-41f9-aed6-2a5d4b4b1bf6">
<img width="1225" alt="image" src="https://github.com/HARPgroup/HARParchive/assets/104520197/2ff1af46-865c-4e9d-83fd-ea031fccbdcc">

- Are there any columns of the table that can be removed when displaying alongside this map?
- It looks like there might be an incorrect 90-day base flow value for seg 7 in the table but the equation handles it correctly 
- Would it be helpful to display values in the table in the same units? (mg/mgd for all)

**Comment by rburghol** [comment]
Thanks for the heads up on this @glenncampagna -- I agree this looks suspicious.  I am doing some model diagnostics now and then I'll rerun to see what gives.

**Comment by rburghol** [comment]
Glenn -- the bad segment was rerun and now has data that makes sense.  I am rerunning the segments downstream of it now, and they should be done in a bout 30 minutes (2:30 EST).  Thanks for seeing that anomaly!

**Comment by rburghol** [comment]
@glenncampagna Now, to your questions:
- Can be removed? No, looking at them, they all seem relevant, and as our objective is to use the table to explain the equations, I think they all need to be there (but their names could be made human readable for this demonstration)
- Segment 7 is now fixed, and the final watershed in the system is finishin the zero rerun. All segment in the Appomattox with impoundments have had their summary scripts rerun since PR https://github.com/HARPgroup/om/pull/545
- MGD for all rate columns would be a really good idea (convert from CFS for flows), and then they will paior more nicely with MG  for the Storage column.

**Comment by glenncampagna** [comment]
### Lake Chesdin Updates
- Thanks for getting back to me @rburghol , here's the updated visuals and table with the fixed segment 
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/7f0bd611-67e7-42b7-8227-76607f24b9ab)
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/11b5bc11-6ee7-4e51-b68e-4a5a6d2128ec)
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/5e8c2844-600d-45b6-ab88-b0297491c5e7)

**Comment by glenncampagna** [comment]
### Carvins Wshed Map & Table after Ordering by cumulative withdrawal 
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/fbc46dc2-3978-41fb-81c3-4bb39d5cd3b5)
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/3e70498e-4c37-4d5e-b8b4-3484ebe3b75a)

**Comment by glenncampagna** [comment]
### Example with Outputs Linked 
Render used: 
```
rmarkdown::render("~/Desktop/GitHub/HARParchive/HARP-2023-Summer/WaterAvailability/WaterAvailability_CaseStudies.Rmd", 
                  output_file = "~/Desktop/HARPteam23/WAcasestudies_knit_runid11_runid0_0.9.docx",
                  output_format = "word_document",
                  params = list(
                      outlet_list = c("PL3_5360_5250", "JU4_7000_7300", "JA5_7480_0001", "YP3_6670_6720", "OR3_7740_8271", "PU4_3970_3890"),
                      demand_scenario = 'runid_11', 
                      baseline_scenario = 'runid_0', 
                      mif_coef = 0.9, 
                      Smin_analysis = TRUE,
                      write_Qavailable = FALSE, 
                      write_outputs = c("local", "github")))
```
**Table 1: WA eqn breakdown**
- CSV:
- flextable:

**Table 2: Case study segments**
- CSV:
- flextable:

**Table 3 example: Case study watershed ()**
- CSV:
- flextable:

**Table 4 example: Case study watershed for L90 ()**
- CSV:
- flextable:

**Table 5: Smin method comparison**
- CSV:
- flextable:

**Table 6: Segments where Smin in VAhydro needs updating**
- CSV:
- flextable:

**Plot example (L90 for )**

**Map example (L90 for )**
