### ISSUE TITLE
Week of 2/14/2024

### ISSUE THREAD

**Issue by glenncampagna** [HARPgroup/HARParchive#1172]
**WSP Summaries & DF Generator**:
- [ ] Caching NHD data to save time using `memoise` package HARPgroup/HARParchive#1163 
- [ ] Incorporate updated foundational data w/ gw_frac
- [ ] Debug basemap function within mapgen HARPgroup/HARParchive#1133 
  - [ ] Test w/ previously non-working origins and update HARPgroup/HARParchive#1130 
- [ ] Modularize mapping function https://github.com/HARPgroup/HARParchive/issues/1106#issuecomment-1749533265
  - We can define multiple functions within the same file for tidiness 
- [ ] Create table configurations that tell our table what to show, add to config

 
**Water Availability**:
- [ ] Water Availability Case Studies HARPgroup/HARParchive#1156 
- [ ] Test om summaries including Carvins to make sure this is resolved HARPgroup/om#525 
- [ ] Re-export Smin for runid_13 #1159 
- [ ] Complete first draft for applicable sections of WA white paper (Smin, baseline, specific examples) HARPgroup/HARParchive#1149
