### ISSUE TITLE
Week of 7/22/2024

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HARParchive#1324]
- [ ] Testing:
   - [ ] @mwdunlap2004 log into deq2 and generate precip series for missing precip data sources for USGS gage basins that you are analyzing (mentioned in modeling meeting on Wednesday)
   - [ ] RWB generate multiple basins for `geo` workflow with ratings
- [ ] Implement changes from last weeks code review
- [ ] Workflows:
   - [ ] @rburghol finish workflow for simple lm in `geo` https://github.com/HARPgroup/model_meteorology/issues/65
   - [ ] Full team review of basic raster processing outline https://github.com/HARPgroup/model_meteorology/issues/50
   - [ ] Preliminary review of raster processing
   - [ ] RWB create outline of steps in workflow amalgamate https://github.com/HARPgroup/model_meteorology/issues/66
   - [ ] Finalize workflow for baseflow separation method.  https://github.com/HARPgroup/model_meteorology/issues/60
- [ ] Discuss breaking into teams of 2 to focus on Baseflow workflow and Raster processing
