### ISSUE TITLE
2021/12/21-22 Configure CBP HSPF p532c to run Extended time period

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HARParchive#142]
- [x] Identify Configuration files needed for new run see: https://github.com/HARPgroup/HARParchive/wiki/Hspf_cbp_rundata
- [x] Create scenario files (see details at #145):
  - [x] `config/control/river/p532sova_2021.con`
  - [x] `config/control/land/p532sova_2021.con`
- [x] Update scenario files
  - [x] Update dates in blocks to use 2005 input files for times running to 2021 in river `*.con` file
  - [x] Update dates in blocks to use 2005 input files for times running to 2021 in land `*.con` files
- [x] Write script to create and populate meteorology config directory  see #144 
  - [x] WDMs go in: /input/scenario/climate/met/[met scenario name]
  - [x] Usage: `./make_met_scenario.sh [met_scenario_name] `
  - **note:** met scenario name does NOT have to be the same as model scenario name (i.e. old version used *xyz* prefixes to reference they were using the XYZ met model)
- [x] Update scenario files to use new met scenario 
- [x] Test Scenarios
  - [x] For debugging purposes see: run UCIs #147 
  - [x] Can the new scenario run with the old timespan?
    - `nano ../../config/control/land/p532sova_2021.con`
    - set "TIME" block to end `2005 12 31`
    - `./run_lug.csh p532sova_2021 JL2_6850_6890`
    - `./run_land.csh p532sova_2021 JL2_6850_6890`
    - YES.  However, need to do a copy of N* landseg WDMs to A* WDMs (see issue #146)
      - NO.  Fails with ` Error in FILES block - Return code 2`
    - Check off these in .con file with date ending 2005, but tables extended to 2021:
  - [x] Test with date ending 2007, and tables extended to 2021:
    - [x] Had to edit .con file (land) to change CALIBSCEN block to : `CALIBSCEN \n p532sova_2021 \n END CALIBSCEN`
    - [x] Verify the output WDM (e.g. forA51800.wdm in tmp/wdm/for/p532sova_2021): 
      - `cd tmp/wdm/for/p532sova_2021` 
      - `wdimex`
      - `forA51800.wdm`
      - `/usr/local/lib/hspf/message.wdm`
  - [x] Test with date ending 2009, and tables extended to 2021:
  - [x] Can the new scenario run with the new timespan to 2020?
    - YES
    - ~Was NO. !See #145
