### ISSUE TITLE
HARP Weekly 2022/07/25

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HARParchive#358]
- [ ] Update on last week #306 
  - [ ] #312
    - [ ] renaming "alias" for Qout
    - [ ] wd_mgd
    - [ ] ps_mgd
    - [ ] etc.
    - [ ] RWB to add link to the old OM R files to use as our template for hsp2 river flow analysis summary script.
  - [ ] Integrate with existing outflow methods (generate L90, L30, etc)
- [ ] #307
    - [ ] Quantify differences
    - [ ] visualize differences
  - [ ] Basic training in `cbp` function helper 
  - [ ] Each analyst pick a **headwater** HUC8 watershed to run from command line.
- [ ] Python coding, for real this week. 
  - [ ] Dev environment: https://github.com/HARPgroup/HSPsquared/issues/6
  - [ ] Overview of special actions: https://github.com/HARPgroup/HSPsquared/issues/5
  - [ ] Object model outline: https://github.com/HARPgroup/HSPsquared/issues/7
- [ ] Focus groups:
  - [x] FTABLE group kickoff #331
  - [ ] hsp2 group kickoff https://github.com/HARPgroup/HSPsquared/issues/5
  - [ ] Harvesting and analytics group next steps #312
