### ISSUE TITLE
HARP Weekly 8/2/2022

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HARParchive#377]
- [x] Update on last week #306 
- [x] Data Export scripts:
  - [x] River: #312
    - [x] RWB to add link to the old OM R files to use as our template for hsp2 river flow analysis summary script.
  - [ ] Identify where in the `h5` file that the wd_mgd (DIVR, DIVA) and ps_mgd (
  - [ ] Integrate with existing outflow methods (generate L90, L30, etc)
- [ ] #307
    - [ ] Quantify differences
    - [ ] visualize differences
  - [ ] Basic training in `cbp` function helper 
  - [ ] Each analyst pick a **headwater** HUC8 watershed to run from command line.
- [ ] Python coding, for real this week. 
  - [ ] Scoping code: https://github.com/HARPgroup/HSPsquared/issues/12
  - [ ] Dev environment: https://github.com/HARPgroup/HSPsquared/issues/6
  - [ ] Overview of special actions: https://github.com/HARPgroup/HSPsquared/issues/5
  - [ ] Object model outline: https://github.com/HARPgroup/HSPsquared/issues/7
- [ ] FTABLE Work #331:
  - [ ] Test the non-province specific method/set of equations for phase 5 FTABLEs (i.e., single equation or physiographic province specific):
    - [ ] present detailed examination of differences in the Roanoke test case. Document here (images and tables)
    - [ ] Add a northern rivers comparison with segment: JL2_6850_6890
  - [ ] Generate more test cases in R
  - [ ] Decide on data model for storing FTABLE in VAHydro.

**Comment by glenncampagna** [comment]
Use and Ex for Land Data export script:
batch_harvest_land.bat
From directory: /opt/model/p53/p532c-sova
Use: batch_harvest_land.bat [scenario] [river seg]
Example: bash ~/HARParchive/HARP-2022-Summer/AutomatedScripts/batch_harvest_land.bat hsp2_2022 OR1_7700_7980 
Calls: detect_data_source.R , export_hsp_h5.R
Output: pwater and iwater csv files located at /media/model/p532/out/land/hsp2_2022/(pwater or iwater)
