### ISSUE TITLE
Handle PS and WD (DIVR) in data harvest to _hydr.csv file

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HARParchive#541]
Based on work in #312 
### Intro:  
The rchres/hydr routines can reject some demand from OUTDGT, so the OUTDGT should be thought of as demand, and the RCHRES/HYDR subroutines in hsp2 work with demand() function and data `o`, `ro`, and also conditionally adds the contents of `irr` to both `o` and `ro`. The `_hydr_()` stashes `o` each timestep as variables `O1`, `O2`, `O3` and `ro` as `RO` in the `hdf5` data table.

### Tasks:
- [x] demand_mgd: the amount of requested withdrawals (may or may not be the same as *actual* withdrawal)
  - divr/diva from WDM
  - demand_mgd = divr + diva 
- [x] wd_mgd: the amount of actual withdrawal from the stream -- based on hydr timeseries, this is just a unit conversion of one or more of the ROVOL columns?
  - Update: we are assuming `wd_mgd = RO - O3` (in hydr table)
- [x] Confirm units for ps and wd (see below)
- [x] Lay out order of scripts that need to be run for processing of demand, wd, and ps 
  All scripts are in place and working now, we just need to be careful with the order we are running things in 
- [x] Make simple flowchart showing this order ^ for visualization 
- [x] Test code with model and push to git

### Confirming Units for diversions/withdrawals and point sources
From River UCI file:
![image](https://user-images.githubusercontent.com/104520197/190209961-4736a0c7-2827-4b39-9227-8d24aca1137d.png)
Withdrawals/Diversions are given type `OUTDGT`
![image](https://user-images.githubusercontent.com/104520197/190210010-74072ad5-3f93-49f9-b8fe-a586e8f95eae.png)
Point sources are given type `IVOL`
From HSPF manual:
![image](https://user-images.githubusercontent.com/104520197/190210060-234f2c89-bb89-46dd-b224-6ecb1b94f31a.png)
OUTDGT has units of `cfs`
and from our Data Dictionary #237 : `IVOL = sum of inflows to the RCHRES [ac.ft/ivld]`
We found that both point sources and diversions are given as daily data, so:
- Point sources = `ac-ft/day`
- Withdrawals/diversions = `cfs`
- Hsp2 code,  
  - see `def demand()` in https://github.com/HARPgroup/HSPsquared/blob/master/HSP2/HYDR.py
  - see adding of irrigation demands to one of the `o` entries, and also adding irr demands to `ro`

### Test Case
- We can use the Occoquan dam has non-zero withdrawals
- Download all data from here:
  - `wget https://deq1.bse.vt.edu/hsp2/wd_river.tar.gz`
  - `tar -xvf wd_river.tar.gz`
- run the following:
 - `hsp2 import_uci PL3_5250_0001.uci PL3_5250_0001.h5`
  - `hsp2 run PL3_5250_0001.h5`
Result from test case: divr contains data while diva = 0, and O1 and RO columns of hydr match divr values

**Comment by rburghol** [comment]
@glenncampagna sent an email - let's video conf

**Comment by juliabruneau** [comment]
### Adding ps_flow and demand to hydr.csv:

The conversion script has been modified in the following way:
* **ps_flow** is converted to mgd and expanded to hourly data
* **divr** and **diva** are summed together as 'demand', converted to mgd, and expanded to hourly data
* both `ps_mgd` and `demand_mgd` are now added to the hydr table, where OVOL3 is 'Qout' in cfs

Arguments: `Rscript [script location] [river seg] [general output file path]`
Ex: `Rscript HARParchive/HARP-2022-Summer/AutomatedScripts/hsp_hydr_conversion.R PL3_5250_0001 /media/model/p532/out/river/hsp2_2022`

Results:
```
juliasb@deq2:/media/model/p532/out/river/hsp2_2022/hydr$ head  PL3_5250_0001_hydr.csv
"index","DEP","IVOL","O1","O2","O3","OVOL1","OVOL2","OVOL3","PRSUPY","RO","ROVOL","SAREA","TAU","USTAR","VOL","VOLEV","date","hour","day","month","year","ps_mgd","demand_mgd","Qout"
2001-01-01 01:00:00,27.3273849487305,27.2538757324219,73.6630477905273,0,0,6.08785533905029,0,0,0,73.6630477905273,6.08785533905029,208.997680664062,3.60031890522805e-06,0.00136303226463497,2196.166015625,0,2001-01-01,1,1,1,2001,0,47.6099010479736,0

```
Files needed for the script:
* `PL3_5250_0001_divr.csv` (in h5: /TIMESERIES/TS3007)
* `PL3_5250_0001_diva.csv` (in h5: /TIMESERIES/TS3008)
* `PL3_5250_0001_psflow.csv` (in h5: /TIMESERIES/TS3000)
* `PL3_5250_0001_hydr.csv` (in h5: /RESULTS/RCHRES_R001/HYDR)

Potential next steps: 
* We can modify the `batch_harvest_river.bat` script to also generate the diva.csv file, and thus that script would generate all the needed csvs and then convert them and add the wanted columns to the hydr.csv.

**Comment by juliabruneau** [comment]
### CONCLUSION

The hydr.csv tabe will include the following values:

"_Column name (origin)_"

`Qout` (OVOL3)
`wd_mgd` (RO)
`ps_mgd` (/TIMESERIES/TS3000)
`demand_mgd` (sum of divr; /TIMESERIES/TS3007, diva; /TIMESERIES/TS3008)

* The current assumption is that RO = actual withdrawals
* From the manual:
![image](https://user-images.githubusercontent.com/104520318/192856892-a10e83f4-a7fe-4e49-b888-5ff5fec680de.png)

These will be included in the table using the script detailed here: #522 (sqdlf function), and the conversion script.

**Comment by rburghol** [comment]
@juliabruneau I wanted to propose a change to the above:
- I believe that `wd_mgd =  RO - OVOL3` instead of using `wd_mgd = RO`. 
- According to the manual, RO is the *total outflow* from the RCHRES, which includes flows out of the stream **and** the withdrawal.  
- There may be some single variable that can take the place of `RO - OVOL3` but I don't know what it is, and I think this is teh most straightforward calc I can make.  
Please let me know your thoughts.

**Comment by glenncampagna** [comment]
### Order of scripts to run for processing demand, wd, and ps
Use `export_hsp_h5.R` to export the HYDR table as a csv
Use `export_hsp_h5.R` to export the divr table as a csv (DSN 3007)
Use `export_hsp_h5.R` to export the diva table as a csv (DSN  3008)
Use `export_hsp_h5.R` to export the ps table as a csv (DSN  3000)
Use `join_col.R` to join divr column to hydr table 
Use `join_col.R` to join diva column to hydr table 
Use `join_col.R` to join ps column to hydr table
Use `hsp_hydr_conversion.R` to add year, month, day, hour, Qout, wd_mgd, demand _mgd, and ps_mgd to hydr file

**Comment by glenncampagna** [comment]
### Testing the workflow above  
Testing done in my home directory to bypass current permission errors 
Starting with `PL3_5250_0001.h5`

`Rscript /opt/model/HARParchive/HARP-2022-Summer/AutomatedScripts/export_hsp_h5.R PL3_5250_0001.h5 PL3_5250_0001_hydr.csv /RESULTS/RCHRES_R001/HYDR/table`

`Rscript /opt/model/HARParchive/HARP-2022-Summer/AutomatedScripts/export_hsp_h5.R PL3_5250_0001.h5 PL3_5250_0001_divr.csv /TIMESERIES/TS3007/table`

`Rscript /opt/model/HARParchive/HARP-2022-Summer/AutomatedScripts/export_hsp_h5.R PL3_5250_0001.h5 PL3_5250_0001_diva.csv /TIMESERIES/TS3008/table`

`Rscript /opt/model/HARParchive/HARP-2022-Summer/AutomatedScripts/export_hsp_h5.R PL3_5250_0001.h5 PL3_5250_0001_ps.csv /TIMESERIES/TS3000/table`

`Rscript ~/HARParchive/HARP-2022-Summer/AutomatedScripts/join_col.R PL3_5250_0001_hydr.csv PL3_5250_0001_divr.csv values divr_cfs header`

`Rscript ~/HARParchive/HARP-2022-Summer/AutomatedScripts/join_col.R PL3_5250_0001_hydr.csv PL3_5250_0001_diva.csv values diva_cfs header`

`Rscript ~/HARParchive/HARP-2022-Summer/AutomatedScripts/join_col.R PL3_5250_0001_hydr.csv PL3_5250_0001_ps.csv values ps_afd header`

... more to come

**Comment by glenncampagna** [comment]
Question for @rburghol: is the above processing of an h5 into a hydr with all of the columns shown something that we want to incorporate into one of our model scripts to have it done automatically? Maybe in the `run_river.csh` script? .. probably the new one I see for phase 6 at `/opt/model/p6/cbp_wsm/run/standard`.. ? If so, let me know if this is something you'd like drafted

**Comment by glenncampagna** [comment]
### Clarifications before digging into Meta-Model work:
I am getting started on incorporating the withdrawal and ps processing into the meta-model framework. I first took a look through the scripts to get a feel of the process, and noticed that the 1st and 3rd scripts in`/opt/model/meta_model/models/hsp2_cbp6/river/link` act to export the hydr table from the h5 as a csv and then run the conversion script on that hydr csv, respectively. These are `01_export_hydr` and `03_convert_hydr`. These 2 steps also happen to be the first and last steps of this withdrawal and ps processing, and I was wondering if the best place to incorporate this might be in this `link `directory? I believe you suggested working in the `analyze` directory in yesterday's meeting, but this seems like it might be a logical spot for this process
