### ISSUE TITLE
HARP Weekly 9/26/2022

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HARParchive#559]
- [ ] Lightning check-in: today is a Work Session type meeting.
- [ ] FTABLES sub-tasks #331 
  - [ ] vahydro floodplain estimation (quick and dirty) #547
  - [ ] Best fast estimation procedure from available data: i.e. based on NHD/NWM sources, #545
  - [ ] Test method 1 and 2 against DEM method #546
- [ ] HYDRO etc #482 
  - [ ] New model runtime controller https://github.com/HARPgroup/meta_model/issues/1
  - [ ] full summary: #556
