### ISSUE TITLE
Week of 1/2/2023

### ISSUE THREAD

**Issue by juliabruneau** [HARPgroup/HARParchive#687]
Winter Break Onboarding meeting at 3 pm 1/4/2023. 

- [ ] FTABLE - batch + REST
  - [ ] Final creation
  - [ ] Add record of table creation, and save JSON ftable as `proptext`
- [x] Successful testing of summary scripts #556 
  - [ ] Final testing within the meta-model
- [ ] Creating new sub-watersheds & Analyzing A collection of basins
  - [ ] Create Data Dictionary for the relevant files in this https://github.com/HARPgroup/cbp_wsm/issues/85
  - [ ] #648
  - [ ] Store hspf/hsp2 data on the VAHydro model object?  At minimum vahydro data should be used to store a record of the creation of the model entity, and whether or not the individual parameter tables are created.  
  - [ ] Glenns meta-model check in
  - [ ] Formatting data for watershed overviews (base on minor basin appendices from SWRP?)
     - https://github.com/HARPgroup/HARParchive/issues/659
- [ ] Start working on the accomplishment summary #659 

**Onboarding meeting:**
- [ ] ...
