### ISSUE TITLE
Week of 1/30/2023 & 2/6/2023

### ISSUE THREAD

**Issue by juliabruneau** [HARPgroup/HARParchive#748]
This work was started this week and it will continue next week. After we have successfully finished with our finalization, we can switch the focus to the new analytical work.

Finalizing previous work:
- [ ] elfgen_huc() in summary script https://github.com/HARPgroup/HARParchive/issues/556 
  - [ ] Need to ask Rob & Joey about this!
- [ ] Final testing on add_sub_subsheds.R https://github.com/HARPgroup/cbp_wsm/issues/85 
  - [ ] Perform testing on _3 diff scenarios_ (+fgrep) and report about it
- [ ] Manually implement changes to the meta model 
  - [ ] Test the new version of meta model with empty link directory (with those functions happening in river/run) 
  - [ ] Flow chart info session (between analysts), Monday 2/6
- [ ] Updating master list of Scripts and their Uses: https://github.com/HARPgroup/HARParchive/issues/505 
  - [ ] Add the meta-model flow to this issue as well

Coming up:
- [ ] Schedule a meeting with @jdkleiner about starting the QA, reference: https://github.com/HARPgroup/HARParchive/issues/736

**Comment by glenncampagna** [comment]
### Weekly Progress
- Re-organized and tested the `meta_model` pull request for demand/wd/ps processing to account for Rob's changes in `river/run`, the next step will be manually implementing them into the main branch 
- The summary routine with both `summarize_values.R` and `summarize_figures.R` can now be added to `hsp2_cbp6/river/analyze/04_analysis` and `hspf_cbp6/river/analyze` -- once we test elfgen_huc(). #742 
- Analyst check-in about Glenn's meta-model flowchart and recent changes

**Comment by glenncampagna** [comment]
### Meta-model flowchart of demand/wd/ps processing
![image](https://user-images.githubusercontent.com/104520197/217079697-6b7222c3-fc8a-43ff-985c-119d709f1cc2.png)

**Comment by jdkleiner** [comment]
Excellent! Love the flowchart. I'm looking forward to these items getting wrapped, and then we can move into generating analytics in R Markdown.
