### ISSUE TITLE
Week of 2/13/2023

### ISSUE THREAD

**Issue by juliabruneau** [HARPgroup/HARParchive#754]
Weekly Meeting at 3:15 pm on Wednesday

- [ ] Working through permission issue and other errors in https://github.com/HARPgroup/HARParchive/issues/556#issuecomment-1428546522 
  - [ ] Verify elfgen_huc() works based on Joey's comments
- [ ] Start investigating the Rmarkdown file: https://github.com/HARPgroup/vahydro/blob/master/R/examples/scenario_vs_scenario.Rmd in https://github.com/HARPgroup/HARParchive/issues/659 
  - [ ] Brainstorm for new statistical analysis methods
- [ ] Verify that we can run the Rscript: `model_mapper.R` https://github.com/HARPgroup/HARParchive/issues/749

**Comment by glenncampagna** [comment]
### Plan for Meta Model Changes/Updates:

- [ ] Copy all Rscripts to their new/final location in `meta_model/scripts`
- [ ] Move `summarize_values.R` into `hsp_hydr_analysis.R` and use conditional saving for model and model scenario in VAhydro
- [ ] Rename summarize_figures.R as `hsp_hydr_plots.R`
- [ ] Move steps from `river/analyze` to `river/link`: `01_export_ext`, `02_join_hydr`, `03_hydr_conv`
- [ ] Move lines that copy (not move) csvs from temp directory to export directory into `link/99_cleanup`
- [ ] Integrate summary routine as `04_hydr_metrics` and `05_hydr_plots` in `analyze`

**Comment by glenncampagna** [comment]
### Meta model test
Run command: `~/meta_model2/run_model hsp2_cbp6 hsp2_2022 JU1_6300_6650 auto river`
The daily hydr csv produced:
```
hydr <- fread('JU1_6300_6650_hydrd_wy.csv')
head(hydr, 2)
                 index      DEP     IVOL O1 O2       O3 OVOL1 OVOL2    OVOL3
1: 1984-10-01 11:30:00 1.321198 26.95258  0  0 262.1584     0     0 21.35172
2: 1984-10-02 11:30:00 1.316555 18.58666  0  0 259.6554     0     0 21.62769
         PRSUPY       RO    ROVOL    SAREA       TAU     USTAR      VOL
1: 0.4854855000 262.1584 21.35172 225.2343 0.5327846 0.5233888 273.6329
2: 0.0008896819 259.6554 21.62769 225.1049 0.5315401 0.5234151 272.3417
        VOLEV       date hour day month year divr_cfs diva_cfs      ps_afd
1: 0.02777563 1984-10-01 11.5   1    10 1984        0        0 0.003705877
2: 0.02599458 1984-10-02 11.5   2    10 1984        0        0 0.003705877
       Qout wd_mgd     ps_mgd demand_mgd Qbaseline wd_imp_child_mgd
1: 258.3558      0 0.00120756          0  258.3539                0
2: 261.6951      0 0.00120756          0  261.6932                0
   wd_cumulative_mgd ps_cumulative_mgd ps_nextdown_mgd
1:                 0        0.00120756               0
2:                 0        0.00120756               0
```
which looks good.. but I got permission errors when trying to run analysis:
```
Running: /home/gcampagna11/meta_model2/models/hsp2_cbp6/river/analyze/04_hydr_metrics hsp2_2022 JU1_6300_6650 /opt/model/p6/vadeq/tmp/scratch/25711
/home/gcampagna11/meta_model2/models/hsp2_cbp6/river/analyze/04_hydr_metrics: Permission denied.
Running: /home/gcampagna11/meta_model2/models/hsp2_cbp6/river/analyze/05_hydr_plots hsp2_2022 JU1_6300_6650 /opt/model/p6/vadeq/tmp/scratch/25711
/home/gcampagna11/meta_model2/models/hsp2_cbp6/river/analyze/05_hydr_plots: Permission denied.
```
I could try running from the newly created user/account harp_glenn but I don't think I'll have access to my home directory so I'll make a pull request

**Comment by juliabruneau** [comment]
### Weekly Progress:

- The `ws_summary_model.rmd` file was modified to include summary stats: 7q10, mn9_10, ml8, and Qout
  - We are running into an error with the gage data, since the years 1998-2000 are missing from the table
  - We are unsure if this is something unique for this specific gage (01643700), or if we should modify the script to make sure it can handle any missing data

**Comment by rburghol** [comment]
@juliabruneau -- thanks for the summary here, and also for creating this issue -- this makes it really easy to track.  
- For the gage error, is that due to gaps in the gage data, that is, 19998-2000 were missing for 01643700 ?  Seems like something we need to be able to handle.  SQL might be useful for this, that is, we can convert our 2 time series (model and gage) into a data.frame, then use a "FULL join" to insure that we have data for all.  
- I am reviewing the meta model integration today. @glenncampagna 
- Can I get some more detail on this `was moved into the meta-model but not tested due to permissions because of the new location of scripts being used` -- Joey and I are the only ones that can do pulls in the `/opt/model/om` directory.  If your scripts work in your home directory, that means that they work (or that we have a high probability of working) but we need to wait till Joey and I have time to test, as we are the only ones that should make changes to `/opt/model/meta_model/`
- Revisiting #443, yes, excellent idea - thanks!
