### ISSUE TITLE
Detailed Work Plan 2023

### ISSUE THREAD

**Issue by gmahadwar** [HARPgroup/HARParchive#853]
Reference to 2023 proposal:  [DEQ_HARP2023_final.pdf] https://github.com/HARPgroup/HARParchive/files/11535837/DEQ_HARP2023_final.pdf)

1. Create maps and tables that display the results of the 2020 State Water Resources Plan and relevant scenarios at multiple coverages

- [ ]  Detailed checklist to come

2. Develop and include the water metrics across scenarios and multiple coverages:

- [ ]  Detailed checklist to come

3. Develop a set of reproducible R markdown scripts that can be knitted together to generate a summary document that is flexible to varying geographic coverages. 

- [ ]  Detailed checklist to come

4. Develop a method of evaluating water availability, and accompanying metrics. 

- [ ]  Detailed checklist to come

5. Develop an error bar analysis for the model that helps answer “what impact does model error have on water availability margin of safety”

- [ ]  Detailed checklist to come
