### ISSUE TITLE
Weeks of 6/12 & 6/20/2023

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HARParchive#898]
- **From last week:**
- [x] Add counties to facility table 
- [x] Add 5-yr avg use to table `wd_current_mgy` (variable from facilities, which is more up-to-date than the `fac_current_mgy` value which is modeled)
- [x] Add permitted capacity to table `vwp_max_mgy`
- [x] permitted capacity labels "non permitted" if value is 0 
- **New:**
- Code conventions (i.e. data retrieval and data display must be separate functions) -- to be covered in Thurs 6/22 meeting
- [x] **FULL JOIN** - note that riverseg in facility model dataframes can be used to get all model data, but ONLY for facilities that have valid model results for the runs in question.  Spatial containments can *also* be used, and will get us data without model runs... which is good.  So, we need to employ both routes and use a FULL JOIN
- [ ] Storing map customizations in VAHydro (ex: http://deq1.bse.vt.edu:81/d.dh/om-model-info/6946324 )
   - Store in `reports/map/...`

**From Monday meeting**

-Mapping tasks
- [x] Address overlapping labels, and prioritize the fips locality names [addressed by changing # data points]
- [x] Reduce clutter of adding river segments to the map - ex. remove rseg names, use dashed lines instead of solid lines
- [x] Anything else that makes the facility maps clear ex. removing small town names and instead showing major roads

-Mapping tasks carried over from last week:
- [x] Continue on the facility map for Appomattox, and explore ways to show
  - [x] facility labels by number - see if there are ways to make labels clear where there are overlapping facilities
- [x] Try zooming in and out to include less or more of the watershed respectively, and see if it still looks good
  - [x] do labels still show clearly? Note: with a larger zoom range, the `label.padding` arg within `geom_label_repel` becomes important to make sure labels don't overlap. Larger zoom needs greater padding to avoid overlaps, and we can create an auto-adjusting var for the padding like we do for scale bar and text sizes
  - [x] etc. (as you see based on what you get): streamlines displayed and text size automatically adjust for some pretty clean mapping 

-Other tasks
- [x] Explore full joins
- [x] Join foundation data with permit capacity data (and other as needed based on carryover from last week:)

**Note - next Thurs 6/22 meeting is planned to be a coding review all hands**

**If you finish the above, here are suggested next tasks:**
- [x] Can you repeat the facility mapping but instead show sources (measuring points)? 
  - [x]  If yes, try number labelling the measuring points. Does labelling by source look messy? Update: yes, labeling by source looks pretty messy with a good amount of overlap where multiple sources are close by. Number labeling is a bit cleaner than using names
  - [x] [skip] Label river segment instead of measuring points. Does this look better?

**Tasks from 6/22 meeting**
- [x] Fix parameters so we can have more then 1 river segment
- [ ]  change parameters for more then one runid 
- [ ]  change legend parameters and adjust table columns
- [x] Fix how we pull the 5 year avg, try to get it from VAhydro now 
- [ ] Continue unchecked tasks from earlier 
- [x] Looking at the token for foundation data set if possible
- [x] Common name for riversegs

**Comment by jdkleiner** [comment]
@glenncampagna Glenn, it looks like you we're never made a member of HARPgroup. You should be receiving an email invite now.

**Comment by glenncampagna** [comment]
Thanks @jdkleiner @gmahadwar , I can access the raw file now

**Comment by glenncampagna** [comment]
### Measuring point labeling & Current State of Table
- I experimented with some tasks toward the bottom of the list before leaving @ lunch today since Megan has some momentum doing map cleanup and labeling 
- Labeling by measuring point is pretty straightforward using the foundational dataset. I omitted most labels to focus on the MPs:
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/aea1dc3a-a285-4c3d-a14f-cc30807a08ab)
Labeling by number was cleaner than by name. Adding unique colors either based on the facility or source type (GW/SW) could add more info to the map without more clutter 
- @EllaF21 finished up our first version of the map-accompanying table yesterday! so I thought I'd share what it looks like as of now
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/c2108696-10db-4b98-9408-397d1a7bd80d)
Now that the county/locality name has been added, we're wondering if we should remove the `Location (Basin)` column and/or the `River Segment` column to have it match what is requested in #853

**Comment by gmahadwar** [comment]
Looking nice! The background layer, names/outlines/improved clarity, river segment hash lines, scale & arrow, and source labels are all looking good. Now that the primary content is addressed, here are some aesthetic suggestions to bring home the maps, for carryover to next week's plan once analysts are back online.

Table edits
- [ ] the 5yr average column would be by source when the table is by source 
- [ ]  upstream/downstream column is relative to the locality/region shown, and applies to sources in the watershed shown that are outside the locality/region boundary 
- [ ] Yes the basin names can be removed from the table
- [ ] Consider - river segment names could be simplified and shown on the tables/maps (so users can reference location when the sources overlap) - not required for the source map/table, but something to consider for future maps/tables

Map edits
- [ ] Locality names no longer need the line to centroid if the smaller towns are not being shown
  - [ ] Is it possible we see how roads or small towns look overlain on this map? Source maps will likely remain watershed focused, but geographic orientation may be helpful on the next maps
- [ ] Yes let's show groundwater and surface water using different colors, and/or different shapes if that looks more clear
- [ ] My preference is that the transparency doesn't change based on withdrawal volume, I'd prefer a standard transparency so it's more obvious where there are areas of high source overlaps. The circle size can still increase by withdrawal volume.
- [ ] Maps will need a title
- [ ] Legend name should be user understandable
- [ ] Can the locality borders/names be a little darker/more defined for easier reading?

Tasks once the above are addressed and all are happy with the maps/tables
- Iterate through the localities and regional planning areas to actually generate all the source maps and tables, but still have the extent be the immediate watershed around the locality/region
- Move to mapping river segments

**Comment by megpritch** [comment]
## Roads
Labeled are the state route numbers. Looking into adding interstates and US highways, and how to differentiate between them without taking up much space.  I am thinking a subtle color change in the label bubble, rather than having "Rte" and "Hwy". Additionally, facility points now have one standard transparency. 
<img width="908" alt="image" src="https://github.com/HARPgroup/HARParchive/assets/104520247/cfbe97df-2732-48cd-ba6c-9d9801dfaff1">

**Comment by EllaF21** [comment]
### Question on table edits ###
@gmahadwar 

We are unsure how to work with this comment on table edits- "upstream/downstream column is relative to the locality/region shown, and applies to sources in the watershed shown that are outside the locality/region boundary". Is there somewhere upstream/downstream data is kept or a way to calculate which source is upstream/downstream? Right now only the initial river segment sources are upstream and all others are downstream.

**Comment by gmahadwar** [comment]
You're right that upstream/downstream as we've categorized it before is typically in relation to the river segment. In this case, we could still use a river segment to decide whether something is upstream or downstream, but the river segment at the most upstream section of the locality or region depicted would be the river segment chosen to set the upstream labels in the table, and conversely the river segment at the most downstream section of the locality or region depicted would be the river segment chosen to set the relative downstream labels. The sources within the locality or region would be N/A for that column. There may be multiple rivers entering the locality shown, so multiple assessments may be needed there.  Let me know if that makes sense, even if it's not quite clear yet how to code that in. The goal is for a given locality/region to be able to identify what sources in the watershed boundary are upstream or downstream of the jurisdictional boundary they may normally consider.

**Comment by EllaF21** [comment]
Thanks! The concept makes sense, we are trying to think of potential ways to code that but are unsure right now. Potentially can be a discussion point for a future meeting.

**Comment by gmahadwar** [comment]
If the VAHydro pull for 5yr avg isn't panning out, this is the line we were using that handles the NA values so they don't reduce the 5yr average calculation. "multi_yr_data" is the foundation data.
``
fiveyr_avg_mgy <- round((rowMeans(multi_yr_data[(length(multi_yr_data)-4):length(multi_yr_data)], na.rm = TRUE, dims = 1)),2)
multi_yr_data <- cbind(multi_yr_data,fiveyr_avg_mgy)
``

**Comment by glenncampagna** [comment]
Thanks @gmahadwar. To try the VAhydro pull method we were wondering what the `ftype` and `bundle` used for measuring points are in VAhydro @jdkleiner ? When trying to access d.alpha we get a 'Site Under Maintenance' message so we can't easily see them ourselves

**Comment by gmahadwar** [comment]
I believe (and jdkleiner can correct me if there's more behind the scenes):
Bundle = "well" or "intake"
Ftypes will vary by use type, ex. "irrigation" or "public_water_supply", but all the options can be found by using the hydroid search page, setting bundle to "surface water intake" and seeing the ftype options.

**Comment by gmahadwar** [comment]
Foundation with 5 year average column has been uploaded.

**Comment by jdkleiner** [comment]
@glenncampagna @rburghol FYI d.alpha should be back up and running now
