### ISSUE TITLE
Week of 6/26/2023

### ISSUE THREAD

**Issue by glenncampagna** [HARPgroup/HARParchive#937]
**Tasks from 6/23 meeting**
- [x] Functionalize the mapping 
  - [x] In map function, want the ability to specify the runid or wd that gets mapped (ex. 5yr avg is mapped as facility bubble size): metric name from the rmd, passed in with `metric` param to the  mapping function, contains both the run id and metric name, ex. `runid_11_wd_mgd`
- [x] Functionalize table generation (in separate function)
- [x] Add config type file that specifies the aesthetics in the maps such that appearance is more easily changed when running in the future: https://github.com/HARPgroup/HARParchive/blob/master/HARP-2023-Summer/mapstyle_config.R
  - [ ] Annotate the aesthetics further, especially where there are very data specific sections
- [ ] VAHydro `map` properties to define customizations where needed for both watersheds and facility/intake maps https://github.com/HARPgroup/vahydro/issues/335
   - [x] Add ability to pass in the bounding box so that if a customized extent exists, it can override the default (ex. full James extent maybe too large, and need custom boundaries) 
   - [ ] HARP analysts please take lead on prototyping and coordinating with Rob/Joey on data model naming conventions etc, as we decide to move beyond BBOX/extent stuff into greater map customizations.
- [x] Update script to pull 5yr average from the predefined column on the new foundation dataset (once uploaded)
- [x] Where appropriate, update package functions to use sqldf (ex. replace ‘subset’)
- [x] Find government source for towns dataset
  - [x] Also save the towns dataset used in the current maps to github,so if the website link breaks the maps are still producible
  - [x] ~~Try pulling this data from VAHydro: bundle: tiger_place, ftype: tiger_place~~
     - ~~Note: this does NOT have population metadata~~
     - ~~http://deq1.bse.vt.edu:81/d.dh/ows-search-by-hydroid?hydroid=&hydrocode_op=contains&hydrocode=&name_op=contains&name=&bundle=tiger_place&fstatus_op=in&fstatus=All&ftype_op=contains&ftype=tiger_place~~
   - [x] JK (6/29/23): Haven't tested it myself, but this may be a good option (R package that retrieves data from a United States Census Bureau API): https://cran.r-project.org/web/packages/tidycensus/tidycensus.pdf

**Moved over from earlier last week:** 
 - [x] Find a reproducible way to map the extent of a locality instead of a watershed
 - [x] Can the locality borders/names be a little darker/more defined for easier reading?
 - [x] Be able to pull region boundaries for mapping
- [x] Check if there's a way to map localities by source and regions by facility. Tables will include source and facility either way.
- [x] Show river segment names (by common name and ID on in the tables/maps (this may already be complete but not checked off)

**Tasks from Analysts:**
- [x] Remove city/town names that match county/locality names from map: done with `sqldf`
- [x] Add usability for locality maps
- [x] Filter facilities/MPs by the extent of the locality
- [x] Add usability for regions and filter facils/MPs by regional geometry
- [x] Do reverse fill for all map types
Maybe: Where there are multiple basins on a map, have a boundary outline to differentiate them (as opposed to using different colors)

**Tasks from 6/29:** 
Code used for minor basins in state plan has good example of legend: https://github.com/HARPgroup/vahydro/blob/master/R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin.mapgen.R
- [x] Change how 5 year avg mgy is presented on legend- make it a select range 
    - [x]  Make zeros smaller
    - [x]  Make sure NA is only in table
    - [x]  Remove decimal place significant digits from legend
    - [x]  Include option for MGD and MGY, with default to display MGD
- [x] Plot basin boundaries for all map types 
- [ ] Implement config file for table as well(possibly more of a future task)
- [ ] Indicate what is customizable and what is not, make readme file for config
- [ ] When this map/table script is ready, have @gmahadwar do a planner test run

Tasks once the above are addressed and all are happy with the maps/tables
- Iterate through the localities and regional planning areas to actually generate all the source maps and tables, but still have the extent be the immediate watershed around the locality/region
- Move to mapping river segments

**Comment by glenncampagna** [comment]
### Comparing VAhydro bbox/extent with the one we generate based on our seg in the rmd 
Map using bbox created using the segment geometry:
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/ce178f78-808d-4111-9b3a-7d0bbe7860f8)
Map using the extent pulled from VAhydro for the same segment accessed using the hydroID and varkey = map:
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/5aba28ac-01f8-49a2-8241-4560bb25ba0b)

**Comment by jdkleiner** [comment]
@glenncampagna This looks like great progress to me! Shows the ability to map using extents stored in VAHydro. A good test will be to try storing some extents in vahydro centered on Henrico county, the map should be able to display the Rsegs in the main stem James River drainage as well as that Chicahominy segment.

**Comment by glenncampagna** [comment]
### REST login error 
We are getting a REST error that seems to indicate the login info has changed:
```
reading from http://deq1.bse.vt.edu/d.dh
RETRIEVING REST TOKEN
Login attempt unsuccessful
```
has the REST password and/or username expired or been changed since yesterday? @jdkleiner @rburghol @gmahadwar 
Thanks

**Comment by gmahadwar** [comment]
Just tested my REST credentials, they are still working, so it's not a password/username issue. 
Second most common for me is a network issue which likely wouldn't affect you all.
Passing to (jdkleiner& rburghol without retagging them)

**Comment by jdkleiner** [comment]
@glenncampagna To confirm, are you all using `rest_uname <- 'restws_p6'`? The PW _should_ be the same

**Comment by glenncampagna** [comment]
Yep @jdkleiner , that's what both me and @EllaF21 are using to try and login to REST

**Comment by glenncampagna** [comment]
It seems like `config.R ` is how we'd want it but I tried removing the 81 from our `site` to make it match yours @jdkleiner but that didn't make a difference, which we expected. Here's the whole config script:
```
# Shared config
library(pander);
library(httr);
library(hydroTSM);
library(sqldf);
library(stats);
# paths and libs
source(paste(basepath,'config.local.private',sep='/'));
source(paste(hydro_tools,"VAHydro-2.0/rest_functions.R", sep = "/"));
source(paste(hydro_tools,"VAHydro-1.0/fn_vahydro-1.0.R", sep = "/"));
source(paste(hydro_tools,"LowFlow/fn_iha.R", sep = "/"));
source(paste(basepath,"auth.private", sep = "/"));#load rest username and password,$
#source(paste(github_location, "cbp6/code","cbp6_functions.R", sep = "/"));

omsite = "http://deq1.bse.vt.edu:81"
#site = "http://deq1.bse.vt.edu:81/d.dh"

site = "http://deq1.bse.vt.edu/d.dh" #tried  removing 81 to retrieve token 

json_obj_url <- paste(site, "node/62", sep ="/")

# base_url <- site

```
We're currently working on things that we can do without REST like creating boundaries/polygons for entire planning regions, functionalizing flextables, and looking for a gov-maintained cities/towns dataset

**Comment by glenncampagna** [comment]
### Reproducible Locality maps
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/461b6cf1-78ee-4015-87a7-e0149437b9c3)
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/374efa6e-0cee-43ed-a37e-22d1c2d706da)
The rmd has added params for `type` and `locality ` for generating maps for localities. The next step will be to do the same for regions, since I have gotten regional geometries by combining (`st_union`) locality geometries into the larger regional geometries

**Comment by gmahadwar** [comment]
Let's get consensus before making a change, but adding this comment now for post-July4th discussion - 
Following up on the 5yr avg NAs and 5yr avg being different than the 2020 values, it makes the most sense for the tables to match the maps. In short, the 5yr avg column would be replaced by a 2020 scenario value column (in mgd or mgy, whichever matches the map).

**Comment by rburghol** [comment]
Classification SQL

```
bins = as.data.frame(c(0.5, 1.0,2.0,5.0,10.0,50,100,500,1000,2000,5000))
bins$classid <- index(bins)
names(bins) <- c("val", "classid")
entity_classes <- sqldf(
  "select a.pid, max(b.classid) as classid
   from wshed_data as a 
  left outer join bins as b 
  on (a.Qout_perm > b.val) 
  group by a.pid"
)

classified_data <- sqldf(
  "select a.*, b.classid 
   from wshed_data as a 
  left outer join entity_classes as b 
  on a.pid = b.pid "
)

```

**Comment by glenncampagna** [comment]
### Updated locality map highlighting all basins intersecting with the locality
![image](https://github.com/HARPgroup/HARParchive/assets/104520197/f7b590e3-7f2b-4061-98f7-09807532f60b)
- The map also shows 2 fewer legend bins than previous with a slightly larger total range of bubble sizes
